"""Behavioural tests for the canonical hand-strength metric.

``strength_metric.strength_percentile`` is the one strength scale every v8
consumer shares (V8_DESIGN section 2); a silent change here re-labels every
training example. These tests pin the endpoints (nuts near 1, air low), the
input validation, and two impossible-by-construction invariants, per the
house rule that a probe is verified against such an invariant before its
answer is believed:

- every percentile lies in [0, 1] (it is a ratio of counts by definition);
- on a fixed board, a hole whose treys rank is strictly stronger never
  receives a lower percentile than a strictly weaker one. Equal ranks are
  excluded: two holes can tie in rank yet block different opponent combos.

All randomness is one seeded ``random.Random``; the metric itself is
seedless (postflop is exact enumeration of ~1081 opponent holdings, so the
fuzz stays at a modest pair count to keep this file fast).

The preflop table (``preflop_percentiles.py``) is generated by
``tools/build_preflop_percentiles.py`` and imported by ``strength_metric``
at module import time; if the generated file is absent every class here
skips instead of the module dying on import. Any other import failure in
``strength_metric`` still raises loudly — the guard checks only for the
generated table, so it cannot mask a real defect.
"""

from __future__ import annotations

import importlib.util
import random
import unittest

from devfun_poker_playground.schema3 import CARD_CODES

_TABLE_AVAILABLE = (
    importlib.util.find_spec("devfun_poker_playground.preflop_percentiles")
    is not None
)
_SKIP_REASON = "preflop table not yet generated"

if _TABLE_AVAILABLE:
    from devfun_poker_playground._vendor.treys import Card, Evaluator
    from devfun_poker_playground.preflop_percentiles import PREFLOP_PERCENTILES
    from devfun_poker_playground.strength_metric import (
        StrengthMetricError,
        canonical_class,
        strength_percentile,
    )

# Seed matches the preflop-table generator's (tools/build_preflop_percentiles
# .py, seed 20260816): arbitrary but fixed, one convention across the repo.
FUZZ_SEED = 20260816
# Ablatable: fuzz breadth. Each pair costs two exact ~1081-holding
# enumerations; 20 keeps the file well under the 60 s budget.
FUZZ_PAIRS = 20


@unittest.skipUnless(_TABLE_AVAILABLE, _SKIP_REASON)
class TestCanonicalClass(unittest.TestCase):
    def test_examples(self) -> None:
        self.assertEqual(canonical_class(["Ah", "Kh"]), "AKs")
        self.assertEqual(canonical_class(["Ks", "Ah"]), "AKo")
        self.assertEqual(canonical_class(["7c", "7d"]), "77")

    def test_order_insensitive(self) -> None:
        for hole in (["Ah", "Kh"], ["Ks", "Ah"], ["7c", "7d"], ["2c", "9s"]):
            self.assertEqual(
                canonical_class(hole), canonical_class(list(reversed(hole)))
            )

    def test_wrong_card_count_is_an_error(self) -> None:
        for hole in ([], ["Ah"], ["Ah", "Kh", "Qh"]):
            with self.assertRaises(StrengthMetricError):
                canonical_class(hole)


@unittest.skipUnless(_TABLE_AVAILABLE, _SKIP_REASON)
class TestValidation(unittest.TestCase):
    def test_malformed_cards_are_errors(self) -> None:
        malformed = (
            ["1h", "Kh"],  # bad rank
            ["ah", "Kh"],  # lowercase rank is not in the contract
            ["Ax", "Kh"],  # bad suit
            ["AH", "Kh"],  # uppercase suit is not in the contract
            ["Ahh", "Kh"],  # too long
            ["A", "Kh"],  # too short
            [7, "Kh"],  # not a string
            ["Ah", "Ah"],  # duplicate within the hole
        )
        for hole in malformed:
            with self.assertRaises(StrengthMetricError):
                strength_percentile(hole, [])

    def test_board_of_two_cards_is_an_error(self) -> None:
        with self.assertRaises(StrengthMetricError):
            strength_percentile(["Ah", "Kd"], ["2c", "3c"])

    def test_board_of_one_or_six_cards_is_an_error(self) -> None:
        with self.assertRaises(StrengthMetricError):
            strength_percentile(["Ah", "Kd"], ["2c"])
        with self.assertRaises(StrengthMetricError):
            strength_percentile(
                ["Ah", "Kd"], ["2c", "3c", "4c", "5c", "6c", "7c"]
            )

    def test_hole_board_overlap_is_an_error(self) -> None:
        with self.assertRaises(StrengthMetricError):
            strength_percentile(["Ah", "Kd"], ["Ah", "7s", "2c"])

    def test_duplicate_board_card_is_an_error(self) -> None:
        with self.assertRaises(StrengthMetricError):
            strength_percentile(["Ah", "Kd"], ["7s", "7s", "2c"])


@unittest.skipUnless(_TABLE_AVAILABLE, _SKIP_REASON)
class TestPostflopEndpoints(unittest.TestCase):
    def test_quad_aces_on_a_safe_board(self) -> None:
        # Quads on an unpaired, straight-flush-proof board beat every one of
        # the 1081 enumerated holdings — the exact value is 1.0; 0.99 is
        # deliberate slack so the pin survives a tie-handling tweak.
        percentile = strength_percentile(["Ah", "Ad"], ["As", "Ac", "2d"])
        self.assertGreater(percentile, 0.99)

    def test_unimproved_seven_deuce_on_overcard_rainbow(self) -> None:
        # 7-high on A-K-9 rainbow. The 0.35 bound is loose (measured ~0.14)
        # and ablatable: it only asserts "air scores low".
        percentile = strength_percentile(["7c", "2d"], ["Ah", "Ks", "9d"])
        self.assertLess(percentile, 0.35)

    def test_seedless_determinism(self) -> None:
        # Exact enumeration: two calls must agree to the last bit. A hidden
        # Monte-Carlo path or global-RNG dependency breaks this.
        first = strength_percentile(["Qh", "Jh"], ["Th", "7d", "2s"])
        second = strength_percentile(["Qh", "Jh"], ["Th", "7d", "2s"])
        self.assertEqual(first, second)


@unittest.skipUnless(_TABLE_AVAILABLE, _SKIP_REASON)
class TestPostflopInvariants(unittest.TestCase):
    """Impossible-by-construction properties, fuzzed with a seeded RNG."""

    def test_range_and_rank_monotonicity(self) -> None:
        rng = random.Random(FUZZ_SEED)
        evaluator = Evaluator()
        strict_pairs = 0
        for _ in range(FUZZ_PAIRS):
            deck = list(CARD_CODES)
            rng.shuffle(deck)
            board_size = rng.choice((3, 4, 5))
            board = deck[:board_size]
            hole_a = deck[board_size : board_size + 2]
            hole_b = deck[board_size + 2 : board_size + 4]

            board_ints = [Card.new(code) for code in board]
            rank_a = evaluator.evaluate(board_ints, [Card.new(c) for c in hole_a])
            rank_b = evaluator.evaluate(board_ints, [Card.new(c) for c in hole_b])

            p_a = strength_percentile(hole_a, board)
            p_b = strength_percentile(hole_b, board)
            for p in (p_a, p_b):
                self.assertGreaterEqual(p, 0.0)
                self.assertLessEqual(p, 1.0)

            if rank_a == rank_b:
                continue  # equal ranks: blockers may legitimately differ
            strict_pairs += 1
            # treys: lower rank is stronger.
            strong, weak = (p_a, p_b) if rank_a < rank_b else (p_b, p_a)
            self.assertGreaterEqual(
                strong,
                weak,
                msg=f"board={board} holes={hole_a}/{hole_b}",
            )
        # Guard against a vacuous fuzz (a probe that never fires proves
        # nothing). Half the pairs is generous slack: rank ties between two
        # random holes are rare.
        self.assertGreaterEqual(strict_pairs, FUZZ_PAIRS // 2)


@unittest.skipUnless(_TABLE_AVAILABLE, _SKIP_REASON)
class TestPreflop(unittest.TestCase):
    def test_endpoints_and_dispatch(self) -> None:
        # An empty board must dispatch to the committed table, verbatim.
        aces = strength_percentile(["Ah", "Ad"], [])
        self.assertGreater(aces, 0.99)
        self.assertEqual(aces, PREFLOP_PERCENTILES["AA"])
        self.assertLess(strength_percentile(["7c", "2d"], []), 0.05)

    def test_suitedness_and_kicker_ordering(self) -> None:
        aks = strength_percentile(["Ah", "Kh"], [])
        ako = strength_percentile(["Ah", "Kd"], [])
        a2o = strength_percentile(["Ah", "2d"], [])
        self.assertGreater(aks, ako)
        self.assertGreater(ako, a2o)

    def test_table_covers_exactly_the_169_classes(self) -> None:
        # Impossible-by-construction: the class universe is derived here
        # from the schema card codes, never restated. 13 pairs plus a suited
        # and an offsuit class per unordered rank pair.
        ranks = tuple(dict.fromkeys(code[0] for code in CARD_CODES))
        expected = {rank * 2 for rank in ranks}
        for low_index, low in enumerate(ranks):
            for high in ranks[low_index + 1 :]:
                expected.add(f"{high}{low}s")
                expected.add(f"{high}{low}o")
        class_count = len(ranks) + len(ranks) * (len(ranks) - 1)
        self.assertEqual(len(expected), class_count)  # 169 for 13 ranks
        self.assertEqual(set(PREFLOP_PERCENTILES), expected)

    def test_table_values_are_strict_probabilities(self) -> None:
        # (0, 1) open: a mid-rank percentile of a nonempty ordering can
        # touch neither endpoint.
        for name, value in PREFLOP_PERCENTILES.items():
            self.assertGreater(value, 0.0, name)
            self.assertLess(value, 1.0, name)


if __name__ == "__main__":
    unittest.main()
